on:
  push:
    branches:
      - master

name: CreatePDFs

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mkrakowitzer/actions-makepdfs@master
      with:
        markdown_dir: doc
        output_dir: tmp
        media_dir: img
    - uses: actions/upload-artifact@v1
      with:
        name: platform-architecture-docs
        path: tmp
