name: Docs to PDF

on:
  push:
    branches:
      - master
    paths:
      - 'doc/**'
      - '.github/workflows/*'

jobs:
  convert_to_pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: convert_to_pdf
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: doc
          output_dir: pdf
          images_dir: doc/img
          image_import: ./img
          build_html: false

      - name: Last release
        id: last_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ github.token }}
      - name: Next Version
        id: version
        uses: technicallyjosh/next-version-action@v1
        with:
          version: ${{ steps.last_release.outputs.tag_name }}

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release with PDFs
        uses: ncipollo/release-action@v1.13.0
        id: create_release
        with:
          allowUpdates: true
          draft: false
          prerelease: false
          makeLatest: true
          tag: ${{ steps.version.outputs.next_version }}
          body: ${{ steps.changelog.outputs.changes }}
          artifacts: pdf/*
          token: ${{ github.token }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
