name: Docs to PDF

on:
  push:
    branches:
      - master
    paths:
      - 'doc/**'
      - '.github/workflows/*'

jobs:
  convert_to_pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: convert_to_pdf
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: doc
          output_dir: pdf
          images_dir: doc/img
          image_import: ./img
          build_html: false
      - name: Last release
        id: last_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ github.token }}
      - name: Next Version
        id: version
        uses: technicallyjosh/next-version-action@v1
        with:
          version: ${{ steps.last_release.outputs.tag_name }}
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.next_version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload pdf files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pdf
          asset_name: docs
          asset_content_type: application/zip
